version: '3'
services:
  {{SERVICENAME}}:
    build: .
    image: nginx:reverse
    container_name: {{SERVICENAME}}
    ports:
      {{PORTCONFIG}}
    networks:
      - {{APPLICATIONNETWORK}}

networks:
  {{APPLICATIONNETWORK}}:
    external: true
