version: '3'
services:
  nginx-reverse:
    build: .
    image: nginx:reverse
    container_name: {{SERVICENAME}}
    ports:
      - "{{PROXYPORT}}:80"
      - "{{PROXYSSLPORT}}:443"
    networks:
      - {{APPLICATIONNETWORK}}

networks:
  {{APPLICATIONNETWORK}}:
    external: true
